# Generated by Django 4.2.1 on 2023-05-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_test_solver', '0002_usertests_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertests',
            name='test_name',
        ),
    ]
